apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim
spec:
  accessModes:
    -ReadWriteMany
  resources:
    request:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
---
version: "3.1"
kind: Service
mongodb:
image : mongo
container_name: mongodb
environment:
  - PUID-1000
  - PGID-1000
volumes:
  - /home/conorsm/mongodb/database:/data/db
ports:
  - 27017:27017
restart: unless-stopped
---
apiVersion: apps/v1
kind: Deployment
matadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo

    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-db
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-db
            